(() => {
  'use strict';
  const $ = id => document.getElementById(id);
  const canvas = $('game'), ctx = canvas.getContext('2d');
  const W = 1280, H = 720, FLOOR = 530;
  const image = path => {const img=new Image();img.src=path;return img;};
  const art = {
    arena:image('../UnityGame/Assets/Resources/Background/arena-waterfalls.png'),
    idle:Array.from({length:4},(_,i)=>image(`../UnityGame/Assets/Resources/Sprites/HeroIdle/hero_idle_${String(i).padStart(2,'0')}.png`)),
    attack:Array.from({length:4},(_,i)=>image(`../UnityGame/Assets/Resources/Sprites/HeroAttack/hero_attack_${String(i).padStart(2,'0')}.png`)),
    guard:Array.from({length:4},(_,i)=>image(`../UnityGame/Assets/Resources/Sprites/HeroGuard/hero_guard_${String(i).padStart(2,'0')}.png`)),
    boss:Array.from({length:8},(_,i)=>image(`../UnityGame/Assets/Resources/Sprites/BossFacingLeft/boss_left_${String(i).padStart(2,'0')}.png`))
  };
  const patternNames=['집게 휘두르기','물결 분사','물기둥'];
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const idleFrame=t=>{const x=t%2.35;return x<1.45?0:x<1.73?1:x<1.84?2:x<2.13?3:0;};
  let mode='menu',phase='choice',hero,boss,elapsed=0,clock=0,last=0,turn=1,pattern=0,timer=0,duration=0,action='',pillarTarget=0,guarded=false,attackApplied=false,bossApplied=false,shake=0,hitFlash=0,damagePopup=null,particles=[],petals=[],sound=false,audio,bannerTime=0;
  let battleId=null,turnResult=null,pendingAction=null,startKey=null,starting=false,requesting=false;
  const api='http://127.0.0.1:8001/api';
  async function send(path,body,headers={}){const response=await fetch(api+path,{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error||`HTTP ${response.status}`);return data;}
  function beep(freq=440,length=.12){if(!sound)return;try{audio ||= new (window.AudioContext||window.webkitAudioContext)();const osc=audio.createOscillator(),gain=audio.createGain();osc.type='triangle';osc.frequency.setValueAtTime(freq,audio.currentTime);osc.frequency.exponentialRampToValueAtTime(Math.max(70,freq*.6),audio.currentTime+length);gain.gain.setValueAtTime(.07,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+length);osc.connect(gain).connect(audio.destination);osc.start();osc.stop(audio.currentTime+length);}catch(_){}}
  function burst(x,y,color,count=15){for(let i=0;i<count;i++)particles.push({x,y,vx:(Math.random()-.5)*260,vy:(Math.random()-.5)*250,life:.55+Math.random()*.3,size:2+Math.random()*4,color});}
  function banner(text,seconds=1){$('banner').textContent=text;$('banner').classList.remove('hidden');bannerTime=seconds;}
  function tip(text){$('tipText').textContent=text;}
  function updateHud(){if(!hero||!boss)return;$('playerHpBar').style.width=hero.hp+'%';$('bossHpBar').style.width=boss.hp+'%';$('staminaBar').style.width=hero.stamina+'%';$('playerHpText').textContent=Math.ceil(hero.hp)+' / 100';$('bossHpText').textContent=Math.ceil(boss.hp)+'%';$('phaseLabel').textContent=boss.stage===1?'PHASE I · 잔잔한 파도':'PHASE II · 성난 파도';$('turnLabel').textContent=`TURN ${String(turn).padStart(2,'0')} · ${phase==='choice'?'PLAYER':'BOSS'}`;$('patternPreview').textContent=`다음 공격: ${patternNames[pattern]}`;}
  function setChoices(){const usable=mode==='playing'&&phase==='choice'&&!requesting;for(const id of ['attackButton','guardButton'])$(id).disabled=!usable;}
  async function reset(){if(starting)return;starting=true;startKey ||= crypto.randomUUID();window.leaderboard.onReset();tip('서버에서 전투를 시작하는 중입니다.');try{const state=await send('/battles',{}, {'Idempotency-Key':startKey});startKey=null;battleId=state.battleId;turnResult=null;pendingAction=null;hero={x:500,y:FLOOR,hp:state.heroHp,stamina:100,facing:1};boss={x:945,hp:state.bossHp,stage:state.bossStage};elapsed=clock=0;turn=state.turn;pattern=state.pattern;phase='choice';mode='playing';timer=0;action='';guarded=false;damagePopup=null;particles=[];petals=Array.from({length:28},()=>({x:Math.random()*W,y:Math.random()*H,s:1+Math.random()*2,speed:10+Math.random()*18}));$('menu').classList.add('hidden');$('result').classList.add('hidden');banner('전투 시작 · 행동을 선택하세요',1.7);tip('다음 보스 패턴을 보고 공격 또는 방어를 고르세요.');setChoices();updateHud();}catch(_){tip('C# 서버에 연결할 수 없습니다. 서버를 실행한 뒤 다시 시도하세요.');}finally{starting=false;}}
  function finish(won){mode=won?'won':'lost';phase='finished';$('resultEyebrow').textContent=won?'BOSS DEFEATED':'BATTLE LOST';$('resultTitle').textContent=won?'승리!':'패배';$('resultCopy').textContent=won?'해안에 다시 평온이 찾아왔습니다.':'패턴을 살펴보고 다시 도전하세요.';$('resultTurns').textContent=turn+'턴';$('resultHp').textContent=Math.ceil(hero.hp)+'%';window.leaderboard.onFinish({won,turns:turn,remainingHp:Math.ceil(hero.hp),battleId});$('result').classList.remove('hidden');setChoices();beep(won?660:120,.3);}
  async function choose(chosen){if(mode!=='playing'||phase!=='choice'||requesting)return;if(pendingAction&&pendingAction!==chosen){tip('이 턴의 전송 결과를 확인 중입니다. 같은 행동으로 재시도하세요.');return;}pendingAction=chosen;requesting=true;setChoices();tip('서버에서 턴을 판정하는 중입니다.');try{const result=await send(`/battles/${battleId}/turns`,{turn,action:chosen});if(result.battleId!==battleId||result.turn!==turn)throw new Error('turn_mismatch');turnResult=result;pendingAction=null;action=chosen;phase='heroAct';timer=duration=chosen==='attack'?.86:.42;attackApplied=false;guarded=chosen==='guard';if(guarded)hero.stamina=clamp(hero.stamina+18,0,100);beep(chosen==='attack'?600:390,.16);tip(chosen==='attack'?'기사가 검을 들어 공격을 준비합니다.':'방어 태세! 이번 보스 공격의 피해가 크게 줄어듭니다.');}catch(_){tip('전송에 실패했습니다. 같은 행동을 다시 눌러 결과를 확인하세요.');}finally{requesting=false;setChoices();}}
  function attack(){choose('attack');}
  function guard(){choose('guard');}
  function hitBoss(){if(attackApplied)return;attackApplied=true;const damage=turnResult.attackDamage;boss.hp=turnResult.bossHp;damagePopup={value:damage,x:boss.x-95,y:FLOOR-205,life:1.15};burst(boss.x-115,FLOOR-120,'#ffe6b5',22);shake=7;beep(500,.18);tip(`공격 적중! ${damage} 피해를 입혔습니다.`);if(turnResult.status==='won'){updateHud();finish(true);return;}if(turnResult.bossStage===2&&boss.stage===1){boss.stage=2;banner('PHASE II · 성난 파도',1.8);}updateHud();}
  function hitHero(amount){if(mode!=='playing')return;if(guarded){burst(hero.x+30,FLOOR-100,'#ffe3b8',16);tip('방어 성공! 피해를 크게 줄였습니다.');beep(340,.14);}else{burst(hero.x,FLOOR-115,'#f5a1a0',20);tip('피격! 다음 패턴을 보고 행동을 선택하세요.');hitFlash=.18;shake=11;beep(145,.25);}hero.hp=turnResult.heroHp;updateHud();if(turnResult.status==='lost')finish(false);}
  function beginBoss(){if(mode!=='playing')return;phase='bossTell';timer=duration=.64;pillarTarget=hero.x;banner(`⚠ ${patternNames[pattern]}`, .64);updateHud();}
  function beginBossAttack(){phase='bossAct';timer=duration=.65;bossApplied=false;beep(230,.19);updateHud();}
  function resolveBoss(){if(bossApplied||mode!=='playing')return;bossApplied=true;if(pattern===0)burst(boss.x-160,FLOOR-115,'#c4edfc',23);else if(pattern===1)burst(hero.x,FLOOR-95,'#a9e8f4',20);else burst(pillarTarget,FLOOR-65,'#afe9fa',25);hitHero(turnResult.bossDamage);}
  function nextTurn(){if(mode!=='playing')return;turn=turnResult.nextTurn;pattern=(pattern+1)%3;turnResult=null;phase='choice';timer=0;action='';guarded=false;hero.stamina=clamp(hero.stamina+13,0,100);setChoices();banner(`TURN ${String(turn).padStart(2,'0')} · 행동 선택`,.9);tip(`다음 공격은 ${patternNames[pattern]}입니다. 공격 또는 방어를 선택하세요.`);updateHud();}
  function update(dt){clock+=dt;shake=Math.max(0,shake-dt*30);hitFlash=Math.max(0,hitFlash-dt);if(damagePopup){damagePopup.life-=dt;if(damagePopup.life<=0)damagePopup=null;}if(bannerTime>0){bannerTime-=dt;if(bannerTime<=0)$('banner').classList.add('hidden');}for(const p of petals){p.y+=p.speed*dt;p.x-=p.speed*.4*dt;if(p.y>H){p.y=-4;p.x=Math.random()*W}if(p.x<0)p.x=W;}particles=particles.filter(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=270*dt;p.life-=dt;return p.life>0;});if(mode!=='playing')return;elapsed+=dt;if(phase==='choice')return;timer-=dt;const progress=clamp(1-timer/duration,0,1);if(phase==='heroAct'){if(action==='attack'&&progress>.47)hitBoss();if(timer<=0)beginBoss();}else if(phase==='bossTell'){if(timer<=0)beginBossAttack();}else if(phase==='bossAct'){if(progress>.42)resolveBoss();if(timer<=0&&mode==='playing'){phase='bossRecover';timer=duration=.4;}}else if(phase==='bossRecover'&&timer<=0)nextTurn();}
  function sprite(img,x,y,w,h,flip=false){if(!img||!img.complete||!img.naturalWidth)return;ctx.save();if(flip){ctx.translate(x+w,0);ctx.scale(-1,1);x=0;}ctx.drawImage(img,x,y,w,h);ctx.restore();}
  function draw(){ctx.clearRect(0,0,W,H);ctx.save();if(shake)ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);const compact=canvas.clientWidth/canvas.clientHeight<1.6;if(!compact){if(art.arena.complete&&art.arena.naturalWidth)ctx.drawImage(art.arena,0,0,W,H);else{ctx.fillStyle='#284559';ctx.fillRect(0,0,W,H);}}for(const p of petals){ctx.fillStyle='#ffdfd6aa';ctx.fillRect(p.x,p.y,p.s*2,p.s);}if(!hero||!boss){ctx.restore();return;}
    ctx.fillStyle='#0b152677';ctx.beginPath();ctx.ellipse(hero.x,FLOOR+4,62,11,0,0,7);ctx.fill();ctx.beginPath();ctx.ellipse(boss.x,FLOOR+3,142,17,0,0,7);ctx.fill();
    if(phase==='bossTell'){ctx.fillStyle='#ff6266aa';ctx.fillRect(pattern===2?pillarTarget-70:boss.x-330,FLOOR-8,pattern===2?140:330,7);}
    const bossFrame=phase==='bossTell'?4:phase==='bossAct'?5+Math.floor(clock*12)%2:phase==='bossRecover'?7:Math.floor(clock*2)%4;
    sprite(art.boss[bossFrame],boss.x-240,FLOOR-461,480,480);
    let heroImage,sw=512,dw=270,drawY=hero.y-259;
    if(phase==='heroAct'&&action==='attack'){let p=clamp(1-timer/duration,0,1);heroImage=art.attack[p<.35?0:p<.53?1:p<.65?2:3];sw=768;dw=405;}
    else if(guarded){heroImage=art.guard[phase==='bossAct'?2:phase==='bossTell'?1:0];sw=768;dw=405;}
    else heroImage=art.idle[idleFrame(clock)];
    sprite(heroImage,hero.x-dw/2,drawY,dw,270,hero.facing<0);
    if(phase==='heroAct'&&action==='attack'){const p=clamp(1-timer/duration,0,1);if(p>.35&&p<.65){ctx.save();ctx.globalAlpha=p<.53?1:(.65-p)/.12;ctx.strokeStyle='#ffe5b9bb';ctx.lineWidth=9;ctx.shadowColor='#e47a66';ctx.shadowBlur=24;ctx.beginPath();ctx.arc(hero.x+105,hero.y-110,97,-1,.8);ctx.stroke();ctx.restore();}}
    if(phase==='bossAct'){const p=clamp(1-timer/duration,0,1);ctx.save();ctx.strokeStyle='#b9e9facc';ctx.lineWidth=12;ctx.shadowColor='#9fdef6';ctx.shadowBlur=22;if(pattern===0){ctx.beginPath();ctx.arc(boss.x-130,FLOOR-130,115,2.1,4.6);ctx.stroke();}else if(pattern===1){for(let i=0;i<3;i++){let x=boss.x-(p*1050)+i*42;ctx.beginPath();ctx.arc(x,FLOOR-70-i*29,20,0,7);ctx.stroke();}}else{ctx.fillStyle='#a6dff3aa';ctx.fillRect(pillarTarget-24,FLOOR-210,48,210);}ctx.restore();}
    for(const p of particles){ctx.globalAlpha=clamp(p.life/.8,0,1);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,7);ctx.fill();}ctx.globalAlpha=1;if(damagePopup){const p=damagePopup,progress=1-p.life/1.15;ctx.save();ctx.globalAlpha=clamp(p.life/.35,0,1);ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='900 52px "Noto Sans KR", sans-serif';ctx.lineJoin='round';ctx.lineWidth=8;ctx.strokeStyle='#3a1720';ctx.shadowColor='#ffbd74';ctx.shadowBlur=22;ctx.strokeText(`-${p.value}`,p.x,p.y-progress*65);ctx.fillStyle='#fff1ba';ctx.fillText(`-${p.value}`,p.x,p.y-progress*65);ctx.restore();}if(hitFlash){ctx.fillStyle=`rgba(255,225,215,${hitFlash*1.3})`;ctx.fillRect(0,0,W,H);}ctx.restore();}
  function loop(now){const dt=Math.min((now-last)/1000||0,.05);last=now;update(dt);draw();requestAnimationFrame(loop);}requestAnimationFrame(loop);
  $('startButton').addEventListener('click',reset);$('retryButton').addEventListener('click',reset);$('attackButton').addEventListener('click',attack);$('guardButton').addEventListener('click',guard);$('soundButton').addEventListener('click',()=>{sound=!sound;$('soundLabel').textContent=sound?'ON':'OFF';beep(550,.1)});
  window.addEventListener('keydown',e=>{const key=e.key.toLowerCase();if(['1','2'].includes(key))e.preventDefault();if(key==='enter'&&mode!=='playing')reset();else if(mode==='playing'&&phase==='choice'){if(key==='1'||key==='j')attack();else if(key==='2'||key==='k')guard();}});
})();
